MVP candidate
technologists-for-progress/52calls-52weeks pull request #30
Opened 2017-01-12 08:17 UTC by jobob2992

2017-01-12 08:19 UTC, jobob2992 commented
So this should have the basic pieces we need for MVP, please review it for correctness and style. I did note in there that this won't be the final solution for insertions to the rep table, but it should be just fine for MVP

2017-01-12 19:18 UTC, xavdid requested changes
Besides assigning values to the wrong key, it looks good!

If you wanted to assign things a little cleaner, you could do something like

```javascript
let user = {}

user.firstName = event.body.firstName || "";
user.lastName = event.body.lastName || "";
...

userObj.Item = user;
```

Either way though.

The other helpful change is that since it looks like we can write w/ es6 features, we should use `let` or `const` over `var`. That beings said, I believe lambda runs `v4.3.2` and there are other changes to make if we're going to use those features.

2017-01-12 19:18 UTC, xavdid commented on functions/submit_user.js
> +    "firstName": "",
minor, but you don't need quotes here. The standard is to do:

```javascript
{
  firstName: '',
  lastName: '',
  ...
```

2017-01-12 19:18 UTC, xavdid commented on functions/submit_user.js
> +    representativeObj.district = data.offices[0].name.match(/[A-Z]{2}-\d\d?$/);
I believe these all need to be `representativeObj.Item.<key>`

2017-01-12 19:18 UTC, xavdid commented on functions/submit_user.js
> +  userObj.phoneNumber = event.body.phoneNumber || "";
Same here, `userObj.Item.lastName`

2017-01-14 01:38 UTC, sethvoltz approved these changes
We doin' this.

2017-01-14 01:39 UTC, merged