Update copy
technologists-for-progress/52calls-52weeks pull request #46
Opened 2017-01-18 20:59 UTC by jontg

Needs reflow before we merge!

2017-01-18 21:06 UTC, sethvoltz requested changes

2017-01-18 21:06 UTC, sethvoltz commented on static/index.html
> +                <p>It's easier than you think to do something to advance women's rights and quality broadly (<a herf="#about">more details</a>).  Calling members of Congress is the most effective way
Do we have have a `how-it-works` page or is this supposed to be `#how-it-works`?

2017-01-18 21:06 UTC, sethvoltz commented on static/index.html
> +                    <li>You make a few quick calls, and your opinion is logged and passed on to your Congress members. (<a href="http://theslot.jezebel.com/how-to-effectively-lobby-your-congressperso
Make this link open a new window/tab: `target="_blank"`

2017-01-18 21:14 UTC, blake213 commented on static/index.html
> +                <p>It's easier than you think to do something to advance women's rights and quality broadly (<a herf="#about">more details</a>).  Calling members of Congress is the most effective way
Code says `<a herf="#about">more details</a>` (herf instead of href)

2017-01-18 21:15 UTC, blake213 commented on static/index.html
> +                <p>It's easier than you think to do something to advance women's rights and quality broadly (<a herf="#about">more details</a>).  Calling members of Congress is the most effective way
`and quality broadly` should that be `equality`?

2017-01-18 23:23 UTC, jontg commented on static/index.html
> +                    <li>You make a few quick calls, and your opinion is logged and passed on to your Congress members. (<a href="http://theslot.jezebel.com/how-to-effectively-lobby-your-congressperso
fixed.

2017-01-18 23:23 UTC, jontg commented on static/index.html
> +                <p>It's easier than you think to do something to advance women's rights and quality broadly (<a herf="#about">more details</a>).  Calling members of Congress is the most effective way
Fixed, fixed and fixed.

2017-01-18 23:24 UTC, jontg commented
@blake213 can you take a look at how this renders locally (you can run `bin/serve` then navigate to `http://127.0.0.1:8080` to see how it lays out)?

2017-01-19 01:15 UTC, sethvoltz approved these changes

2017-01-19 02:58 UTC, merged